### ISSUE TITLE
tn_vdp_v3_v9958 aux pll config

### ISSUE THREAD

**Issue by lintweaker** [lfantoniosi/tn_vdp#10]
Hi,
Thanks for v3 v9958!
Possible issue with the docs regarding programming the Aux PLL
The constraint file states:

IO_LOC "clk_50" 10;       // crystal<br>
IO_LOC "clk_125" 11;       // crystal<br>
IO_LOC "clk_63" 13;       // crystal<br>
`
The Tang 20k schematic shows:
`
CLK0 - PIN10
CLK1 - PIN11
CLK2 - PIN13
`
So, the Aux PLL should be set via:
`
pll_clk O0=50M
pll_clk O1=125M
pll_clk -s
`
?
Thanks.

**Comment by lfantoniosi** [comment]
yeah you are right. updating the docs
