### ISSUE TITLE
32K limit for V9958?

### ISSUE THREAD

**Issue by HeathenUK** [lfantoniosi/tn_vdp#8]
Hi there,

Amazing work, congratulations!

Am I right in thinking that the limiting factor on "VRAM" for the V9958 gateware is the amount of SRAM or BRAM available on the TN9K?

If so - and recognising that you're not targeting this board (yet) - is it possible to create a version with substantially more "VRAM" on the TN20K given the significantly increased on-chip SRAM etc.? I can only assume it's not as easy as increasing reg [7:0] mem_r[0:32767];r to reg [7:0] mem_r[0:131068];

In any case I'm hoping to get a build going on the TN20K of the current source.

Regards,

Greg

**Comment by lfantoniosi** [comment]
https://www.youtube.com/watch?v=Je3N2BwWwb8&lc=
