### ISSUE TITLE
V9958 TN20k

### ISSUE THREAD

**Issue by lintweaker** [lfantoniosi/tn_vdp#9]
First off, great work!
I was about the create an issue regarding porting V9958 32k to the Tang Nano 20k. I saw your video showing this version from 3d days ago, great stuff!
So basically just 2 questions:
- are you planning to release that code?
- Are you using the integrated SDR SRAM for the VRAM?
Thx.

**Comment by HeathenUK** [comment]
And to add a related question - I was going to pick up the existing socket design (which fits the TMS9918 DIP40) and create a V9938/58 version, unless that's cutting across something already planned?

**Comment by lfantoniosi** [comment]
the 9958 version is planned. A 9938 is not exact pin compatible. I still did not finish the 9918 version, don't rush pls.

I don't know the signals I need to generate or read.  it will be good for omega msx but hell no I am not removing a9958/9938 from my MSX2/2+/Tr computers,

Also the SDIP pin headers are non-existent in North America suppliers. I had to get from Ali-express and they are not the cheapest.

**Comment by lfantoniosi** [comment]
This should answer any question: https://www.youtube.com/watch?v=Je3N2BwWwb8&t

**Comment by HeathenUK** [comment]
Yeah, it's for my OmegaMSX I'm thinking of.

G
